version: "3.8"
services:
  onereport:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/onereport
    ports:
      - 8080:5000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: 16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
volumes:
  postgres_data:
