name: onereport
services:
  onereport:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./:/usr/onereport
    environment:
      - SQLALCHEMY_DATABASE_URI =
    ports:
      - "80:5000"
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:16.2-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER =
      - POSTGRES_PASSWORD =
      - POSTGRES_DB =
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
