# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/

name: onereport
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/:ro
      - ../certbot/www/:/var/www/certbot/:ro
      - ../certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - onereport

  # https://mindsers.blog/en/post/https-using-nginx-certbot-docker/
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ../certbot/www/:/var/www/certbot/:rw
      - ../certbot/conf/:/etc/letsencrypt/:rw

  onereport:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 -w 3 "onereport:create_app()"
    environment:
      - SQLALCHEMY_DATABASE_URI=
    expose:
      - "5000"
    env_file: ./onereport/.env
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
